In [34]:
from main import LinearRegression
import numpy as np
import pandas as pd
import seaborn as sns

df = pd.read_csv("Teen_Mental_Health_Dataset.csv")
df.head()

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0

In [35]:
# Creating features  and prediction feature
y = df[['addiction_level']]
x = df.drop(['addiction_level'], axis=1)
x.head(100)

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,depression_label
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,0
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,0
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,0
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,0
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...
95,15,female,1.8,Instagram,6.4,2.4,2.16,1.9,medium,3,6,0
96,13,male,3.1,TikTok,5.4,1.9,3.66,0.4,low,7,4,0
97,13,female,3.5,TikTok,5.2,2.5,2.57,1.1,high,1,6,0
98,18,male,7.4,TikTok,6.4,2.2,3.51,1.0,high,4,5,0
99,16,male,8.0,Instagram,5.5,1.4,2.95,0.3,medium,2,5,0

In [36]:
# one hot encoding
x_cat = x[['gender','platform_usage','social_interaction_level']]
x_cat_encoded = pd.get_dummies(x_cat)
x_num = x.drop(x_cat, axis=1)

X= pd.concat([x_cat_encoded, x_num], axis=1)

X.head()

,gender_female,gender_male,platform_usage_Both,platform_usage_Instagram,platform_usage_TikTok,social_interaction_level_high,social_interaction_level_low,social_interaction_level_medium,age,daily_social_media_hours,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,stress_level,anxiety_level,depression_label
0,False,True,False,True,False,False,True,False,14,7.9,7.4,2.9,3.01,1.5,2,2,0
1,True,False,False,False,True,True,False,False,19,1.9,8.0,2.9,3.22,0.8,8,1,0
2,True,False,False,True,False,True,False,False,17,1.3,7.6,0.5,3.92,0.0,2,4,0
3,False,True,False,False,True,False,False,True,15,7.4,6.9,1.6,3.48,0.8,1,7,0
4,True,False,True,False,False,False,False,True,15,4.7,4.9,3.0,2.37,1.4,3,5,0

In [37]:
ln_reg  = LinearRegression()

ln_reg.fit(X,y)

C:\Users\DELL\AppData\Local\Programs\Python\Python313\Lib\site-packages\numpy\_core\_methods.py:49: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims, initial, where)
C:\Users\DELL\AppData\Local\Programs\Python\Python313\Lib\site-packages\numpy\_core\_methods.py:49: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims, initial, where)
C:\Users\DELL\AppData\Local\Programs\Python\Python313\Lib\site-packages\numpy\_core\_methods.py:49: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims, initial, where)

OverflowError: (34, 'Result too large')

In [ ]:
x_cat_encoded.head(100)
# print(x_cat_encoded.shape)
# print(x_num.shape)
# print(X.shape)